name: Release

on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:
        inputs:
            tag:
                description: 'Tag to release (e.g., v1.0.0)'
                required: true

permissions:
    contents: write

jobs:
    release:
        name: Build and Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run quality checks
              run: |
                  npm run lint
                  npm run format:check
                  npm run typecheck
                  npm run build

            - name: Run tests
              run: npm test

            - name: Get release info
              id: release_info
              run: |
                  # Use provided tag or extract from ref
                  if [ "${{ github.event.inputs.tag }}" != "" ]; then
                    TAG="${{ github.event.inputs.tag }}"
                  else
                    TAG="${{ github.ref_name }}"
                  fi
                  echo "TAG=$TAG" >> $GITHUB_OUTPUT

                  # Extract version without 'v' prefix
                  VERSION="${TAG#v}"
                  echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

            - name: Create package tarball
              run: npm pack

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: docusaurus-plugin-cookie-consent-*.tgz
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag_name: ${{ steps.release_info.outputs.TAG }}
                  name: Docusaurus Cookie Consent ${{ steps.release_info.outputs.TAG }}
                  body: |
                      ## What's Changed

                      Check the [CHANGELOG](https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md) for detailed changes.

                      ## Installation

                      Download the attached `.tgz` file and install it locally:

                      ```bash
                      npm install ./docusaurus-plugin-cookie-consent-${{ steps.release_info.outputs.VERSION }}.tgz
                      ```

                      ## Quick Start

                      Add to your `docusaurus.config.js`:
                      ```javascript
                      module.exports = {
                        plugins: [
                          ['docusaurus-plugin-cookie-consent', {
                            providers: [
                              {
                                type: 'google',
                                id: 'G-XXXXXXXXXX'  // Your Google Analytics ID
                              }
                            ]
                          }]
                        ]
                      };
                      ```

                      ## Documentation

                      - [README](https://github.com/${{ github.repository }}/blob/master/README.md)
                  draft: false
                  prerelease: ${{ contains(steps.release_info.outputs.TAG, 'beta') || contains(steps.release_info.outputs.TAG, 'alpha') }}
                  generate_release_notes: true
